### ISSUE TITLE
Unable to deploy to Heroku

### ISSUE THREAD

**Issue by db-lyon** [SFDO-Tooling/Metecho#2089]
The "Deploy to Heroku" button fails silently.

**Comment by db-lyon** [comment]
I'm brand new to heroku and metecho and I was hoping (perhaps naively) that I'd be able to push it and call it a day. 

Any advice would be appreciated.

**Comment by db-lyon** [comment]
I just ran `heroku config:set DISABLE_COLLECTSTATIC=1` and seem to have made it a bit further. 

No I'm facing a new error. Feels like forward progress, but not totally certain.

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.10/site-packages/environ/environ.py", line 403, in get_value
    value = self.ENVIRON[var_name]
  File "/app/.heroku/python/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'DB_ENCRYPTION_KEY'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/manage.py", line 42, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python3.10/site-packages/django/core/management/base.py", line 95, in wrapped
    saved_locale = translation.get_language()
  File "/app/.heroku/python/lib/python3.10/site-packages/django/utils/translation/__init__.py", line 210, in get_language
    return _trans.get_language()
  File "/app/.heroku/python/lib/python3.10/site-packages/django/utils/translation/__init__.py", line 65, in __getattr__
    if settings.USE_I18N:
  File "/app/.heroku/python/lib/python3.10/site-packages/django/conf/__init__.py", line 87, in __getattr__
    self._setup(name)
  File "/app/.heroku/python/lib/python3.10/site-packages/django/conf/__init__.py", line 74, in _setup
    self._wrapped = Settings(settings_module)
  File "/app/.heroku/python/lib/python3.10/site-packages/django/conf/__init__.py", line 183, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/app/.heroku/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/config/settings/base.py", line 50, in <module>
    DB_ENCRYPTION_KEY = env("DB_ENCRYPTION_KEY")
  File "/app/.heroku/python/lib/python3.10/site-packages/environ/environ.py", line 197, in __call__
    return self.get_value(
  File "/app/.heroku/python/lib/python3.10/site-packages/environ/environ.py", line 407, in get_value
    raise ImproperlyConfigured(error_msg) from exc
django.core.exceptions.ImproperlyConfigured: Set the DB_ENCRYPTION_KEY environment variable

**Comment by davidmreed** [comment]
Hi @db-lyon, sorry about that! Try [this setup documentation](https://metecho.readthedocs.io/en/latest/heroku-setup.html). We'll remove the button, which isn't helpful.

**Comment by db-lyon** [comment]
Thanks @davidmreed! I was able to get everything working eventually. :)
